BurgerStore/Controllers/CartController.cs
using BurgerStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace BurgerStore.Controllers
{
    public class CartController : Controller
    {
        private readonly BurgerStoreDbContext _burgerStoreDbContext;

        public CartController(BurgerStoreDbContext burgerstoredbcontext)
        {
            _burgerStoreDbContext = burgerstoredbcontext;
        }



        public IActionResult Index()
        {
            Guid cartId;
            Cart cart = null; ;
            if (Request.Cookies.ContainsKey("cartId"))
            {
                if(Guid.TryParse(Request.Cookies["cartId"], out cartId))
                {
                       cart = _burgerStoreDbContext.Carts.Include(carts => carts.CartItems).ThenInclude(cartitems => cartitems.Product).FirstOrDefault(x => x.CookieIdentifier == cartId);
                }
            }

            if (cart == null)
            {
                cart = new Cart();

            }
            return View(cart);

        }

        public IActionResult Remove(int id)
        {
            Guid cartId;
            Cart cart = null;
            if (Request.Cookies.ContainsKey("cartId"))
            {
                if(Guid.TryParse(Request.Cookies["cartId"],out cartId))
                {
                    cart = _burgerStoreDbContext.Carts.Include(carts => carts.CartItems).ThenInclude(cartitems => cartitems.Product).FirstOrDefault(x => x.CookieIdentifier == cartId);
                }
            }

            CartItem item = cart.CartItems.FirstOrDefault(x => x.ID == id);

            cart.LastModified = DateTime.Now;

            _burgerStoreDbContext.CartItems.Remove(item);

            _burgerStoreDbContext.SaveChanges();

            return RedirectToAction("Index");
        }






    }
}

BurgerStore/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using BurgerStore.Models;
using Microsoft.EntityFrameworkCore;
using Braintree;

namespace BurgerStore.Controllers
{
    public class CheckoutController : Controller
    {
        private BurgerStoreDbContext _burgerStoreDbContext;
        private EmailService _emailService;
        private SignInManager<BurgerStoreUser> _signInManager;
        private BraintreeGateway _braintreeGateway;
        private SmartyStreets.USStreetApi.Client _usStreetApiClient;


        public CheckoutController(BurgerStoreDbContext burgerstoredbcontext, EmailService emailService, SignInManager<BurgerStoreUser> signInManager, BraintreeGateway braintreeGateway, SmartyStreets.USStreetApi.Client usStreetApiClient)
        {

            this._burgerStoreDbContext = burgerstoredbcontext;
            this._emailService = emailService;
            this._signInManager = signInManager;
            this._braintreeGateway = braintreeGateway;
            this._usStreetApiClient = usStreetApiClient;

        }


        // GET: /Checkout
        public async Task<IActionResult> Index()
        {

            CheckoutViewModel model = new CheckoutViewModel();
            await GetCurrentCart(model);
            if (model.Cart == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(model);

        }

        private async Task GetCurrentCart(CheckoutViewModel model)
        {
            Guid cartId;
            Cart cart = null;

            if (User.Identity.IsAuthenticated)
            {
                var currentUser = await _signInManager.UserManager.GetUserAsync(User);
                model.ContactEmail = currentUser.Email;
                model.ContactPhoneNumber = currentUser.PhoneNumber;
            }

            if (Request.Cookies.ContainsKey("cartId"))
            {
                if (Guid.TryParse(Request.Cookies["cartId"], out cartId))
                {
                    cart = await _burgerStoreDbContext.Carts
                        .Include(carts => carts.CartItems)
                        .ThenInclude(cartitems => cartitems.Product)
                        .FirstOrDefaultAsync(x => x.CookieIdentifier == cartId);

                }
            }

            model.Cart = cart;


        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Index(CheckoutViewModel model)
        {
            await GetCurrentCart(model);

            if (ModelState.IsValid)
            {
                
               
                Order newOrder = new Order
                {
                    TrackingNumber = Guid.NewGuid().ToString(),
                    OrderDate = DateTime.Now,
                    OrderItems = model.Cart.CartItems.Select(x => new OrderItem
                    {
                        ProductID = x.Product.ID,
                        ProductName = x.Product.Name,
                        ProductPrice = (x.Product.Price ?? 0),
                        Quantity = x.Quantity
                    }).ToArray(),
                    ShippingAddress = model.ShippingAddress,
                    ShippingCountry = model.ShippingCountry,
                    ContactEmail = model.ContactEmail,
                    ContactPhoneNumber = model.ContactPhoneNumber,
                    ShippingLocale = model.ShippingLocale,
                    ShippingPostalCode = model.ShippingPostalCode,
                    ShippingRegion = model.ShippingRegion,

                };


                //this is our braintree transaction section

                TransactionRequest transaction = new TransactionRequest
                {
                    //Amount = 1,
                    Amount = model.Cart.CartItems.Sum(x => x.Quantity * (x.Product.Price ?? 0)),

                    CreditCard = new TransactionCreditCardRequest
                    {
                        Number = model.BillingCardNumber,
                        CardholderName = model.NameOnCard,
                        CVV = model.BillingCardVerificationValue,
                        ExpirationMonth = model.BillingCardExpirationMonth.ToString().PadLeft(2, '0'),
                        ExpirationYear = model.BillingCardExpirationYear.ToString()
                    }

                };

                var transactionResult = await _braintreeGateway.Transaction.SaleAsync(transaction);
                if (transactionResult.IsSuccess())
                {



                    _burgerStoreDbContext.Orders.Add(newOrder);
                    _burgerStoreDbContext.CartItems.RemoveRange(model.Cart.CartItems);
                    _burgerStoreDbContext.Carts.Remove(model.Cart);
                    await _burgerStoreDbContext.SaveChangesAsync();

                    //Try to checkout
                    Response.Cookies.Delete("cartId");
                    return RedirectToAction("Index", "Receipt", new { id = newOrder.TrackingNumber });
                }
                for (int i = 0; i < transactionResult.Errors.Count; i++)
                {
                    ModelState.AddModelError("BillingCardNumber" + i, transactionResult.Errors.All()[i].Message);
                }



            }
            return View(model);
        }
    }

}








        



    

BurgerStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BurgerStore.Models;
using Microsoft.EntityFrameworkCore;

namespace BurgerStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly BurgerStoreDbContext _burgerStoreDbContext;
        //private List<Product> _products;

        public ProductController(BurgerStoreDbContext burgerStoreDbContext)   //injection
        {
            _burgerStoreDbContext = burgerStoreDbContext;
            

        }

        [HttpPost]
        public IActionResult Details(int id, int quantity=1)
        {
            Guid cartId;
            Cart cart = null;
            if (Request.Cookies.ContainsKey("cartId"))
            {
                if(Guid.TryParse(Request.Cookies["cartId"], out cartId))
                {
                    cart = _burgerStoreDbContext.Carts.Include(carts => carts.CartItems).ThenInclude(cartitems => cartitems.Product).FirstOrDefault(x => x.CookieIdentifier == cartId);
                }
            }

            if (cart==null)
            {
                cart = new Cart();
                cartId = Guid.NewGuid();
                cart.CookieIdentifier = cartId;

                _burgerStoreDbContext.Carts.Add(cart);
                Response.Cookies.Append("cartId", cartId.ToString(), new Microsoft.AspNetCore.Http.CookieOptions { Expires = DateTime.UtcNow.AddYears(100) });

            }
            CartItem item = cart.CartItems.FirstOrDefault(x => x.Product.ID == 2);
            if (item == null)
            {
                item = new CartItem();
                item.Product = _burgerStoreDbContext.Products.Find(id);
                cart.CartItems.Add(item);
            }

            item.Quantity+=quantity;
            cart.LastModified = DateTime.Now;

            _burgerStoreDbContext.SaveChanges();
            return RedirectToAction("Index", "Cart");
        }

        public IActionResult Index()
        {
            List<Product> products = _burgerStoreDbContext.Products.ToList();
            return View(products);
        }

        //This is the details method connecting to details view
        public IActionResult Details(int? ID)
        {
            if (ID.HasValue)
            {
                Product p = _burgerStoreDbContext.Products.Find(ID.Value);
                return View(p);
            }
            return NotFound();
        }




    }
}

BurgerStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Flavor Town Burgers</title>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="https://bootswatch.com/4/yeti/bootstrap.min.css" />



</head>
<body>

        <nav class="navbar navbar-default navbar-dark bg-success">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Flavor Town Burgers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-lg-auto">
                  <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Shop</a>
                  </li>




                  <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                  </li>

                  <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="Checkout" asp-action="Index">Checkout</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                  </li>

                  <!-- need to figure out how to hide this once I'm logged in-->
                  @if (User.Identity.IsAuthenticated)
                  {
                      <li></li>

                  }
                  else
                  {
                      <li class="nav-item">
                          <a class="nav-link" asp-area="" asp-controller="Account" asp-action="SignIn">Sign In</a>
                      </li>

                  }


                  @if (!User.Identity.IsAuthenticated)
                  {
                      <li class="nav-item">
                          <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">Sign Up</a>
                      </li>
                  }
                  else
                  {

                      <li class="nav-item">
                          <a class="nav-link" asp-area=" " asp-controller="Account" asp-action="SignOut">Sign Out as @User.Identity.Name</a>
                      </li>

                  }


              </ul>



             </div>










    </nav>
    


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Flavor Town Burgers</p>
        </footer>
    </div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/popper.js/dist/umd/popper.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>